### PR TITLE
Support ghc 9.8.

### PR DESCRIPTION
**Pull request by alaendle**

### CODE REVIEW

**Comment by maoe** [comment]
LGTM. Thanks!

**Comment by alaendle** [comment]
@maoe - Since ghc-9.8 is out for a while now, could you crop a new release? ❤️

**Comment by maoe** [comment]
Ah I forgot to make a new release. I'll do it tonight.

**Comment by maoe** [comment]
Released https://hackage.haskell.org/package/influxdb-1.9.3.1

**Comment by alaendle** [comment]
@maoe - Many thanks for you continuous efforts.

**Pull request merged**
