### PR TITLE
apply basic auth for query

### PR DESCRIPTION
**Pull request by Lupino**

### CODE REVIEW

**Comment by maoe** [comment]
Code looks good to me. Did you actually use this change in your environment?

**Comment by maoe** [comment]
This fixes #19.

**Comment by Lupino** [comment]
Yes I use it on my project, which need a basic auth

**Comment by maoe** [comment]
Sounds good. Thanks for your contribution!

**Comment by maoe** [comment]
BTW, don't you use basic auth for writes?

**Comment by maoe** [comment]
Uploaded https://hackage.haskell.org/package/influxdb-1.5.1

**Pull request merged**
